- name: "Create users"
  become: "true"
  rabbitmq_user:
    user: "{{ item.username }}"
    password: "{{ item.password }}"
    vhost: "/"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    tags: "administrator"
    state: "present"
  loop: "{{ rabbitmq.users }}"
  no_log: "true"
  register: result
  changed_when: result.rc > 0
